CLASS zcl_7409_handler DEFINITION PUBLIC FINAL CREATE PUBLIC
  FOR EVENTS OF z7409_r_travel.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_7409_handler IMPLEMENTATION.
ENDCLASS.
